@startuml fileManagerClassDiagram

package storage {
    
    class HighscoreFileManager {
        - static final highscoreFile : File
        + static getFile() : File
        + static writeToHighscore(UserScore, File)
        - static sortUserScores(List<UserScore>)
        - static writeToFile(List<UserScore>, File)
        + static readFromHighscore(File) : List<UserScore>
        + static deleteFromHighscore(String, int, String)
        + static clearHighscore(File)
    }

    class UserScore {
        - name : String
        - score : int
        - date : String
        - difficulty : String
        + UserScore(String, int, String, String)
        + toJson() : String
        + toString() : String
        + getName() : String
        + getScore() : int
        + getDate() : String
        + getDifficulty() : String
    }

    HighscoreFileManager --> UserScore: Uses

}

@enduml
